services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: "unless-stopped"
    container_name: jellyfin
    networks:
      - jellyfin-network
    volumes:
      # Create these directories next to this file
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - type: bind
        source: /mnt/Example
        target: /Example
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - JELLYFIN_PublishedServerUrl=https://example.url.com
    # Docker health checks
    extra_hosts:
      - "host.docker.internal:host-gateway"
  caddy:
    image: caddy:2.11.2
    restart: unless-stopped
    container_name: caddy
    networks:
      - jellyfin-network
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy-etc:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  jellyfin-network:
